### ISSUE TITLE
Task name is null for test case chapter-02/jBPM6-quickstart/src/test/java/com/wordpress/marianbuenosayres/quickstart/ProgrammedProcessExecutionTest.java

### ISSUE THREAD

**Issue by AmitaBorse** [marianbuenosayres/jBPM6-Developer-Guide#2]
I tried executing test case under chapter-02/jBPM6-quickstart/src/test/java/com/wordpress/marianbuenosayres/quickstart named 'ProgrammedProcessExecutionTest.java' . It was successful. But Name and FormName in Task table of jBPM are coming null. Can you please help me with that? Also how to assign task to a group or user using this api?
![jbpmtasktable](https://cloud.githubusercontent.com/assets/20065606/16255269/ecd3ca76-3865-11e6-9759-4bc355d030ae.JPG)

**Comment by marianbuenosayres** [comment]
The ProgrammedProcessExecutionTest doesn't interact with user tasks, so these entries should be from another test you run. However, once you find the right test taht creates these user tasks, the name column for the task table will be assigned according to the node name (the name on the user task activity box), and the formname colum for the task table will be assigned according to the "TaskName" data input value. See the BPMN writting chapter to get information about the tasks data inputs and node names.
